CREATE TABLE IF NOT EXISTS route (
  Id SERIAL,
  NameRu varchar(250) NOT NULL,
  NameEn varchar(250) NOT NULL,
  NameKk varchar(250) NOT NULL,
  FullNameRu varchar(250) NOT NULL,
  FullNameEn varchar(250) NOT NULL,
  FullNameKk varchar(250) NOT NULL,
  Distance  DECIMAL(20,3) NOT NULL,
  Comment varchar(250) NOT NULL,
  OpenReason varchar(250) NOT NULL,
  CloseReason varchar(250) NOT NULL,
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS baseplatform (
  Id SERIAL,
  NameRu varchar(250) NOT NULL,
  NameEn varchar(250) NOT NULL,
  NameKk varchar(250) NOT NULL,
  Polygon DECIMAL(20,3) NOT NULL,
  ProviderId INT,
  Comment varchar(250) NOT NULL,
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS device (
  Id SERIAL,
  FirmWareId INT,
  StabilizerId INT,
  SimcardId INT,
  IMEI INT,
  SerialNumber varchar(250),
  Comment varchar(250),
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);
CREATE TABLE IF NOT EXISTS provider (
  Id SERIAL,
  NameRu varchar(250) NOT NULL,
  NameEn varchar(250) NOT NULL,
  NameKk varchar(250) NOT NULL,
  Address varchar(250) NOT NULL,
  Head varchar(250) NOT NULL,
  PhoneNumber varchar(250) NOT NULL,
  Email varchar(250) NOT NULL,
  Bank varchar(250) NOT NULL,
  BIN varchar(250) NOT NULL,
  BIK varchar(250) NOT NULL,
  DispatcherPhoneNumber varchar(250) NOT NULL,
  TechServicePhoneNumber varchar(250) NOT NULL,
  Comment varchar(250) NOT NULL,
  RegionId INT NOT NULL,
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS stop (
  Id SERIAL,
  NameRu varchar(250) NOT NULL,
  NameEn varchar(250) NOT NULL,
  NameKk varchar(250) NOT NULL,
  Longitude  DECIMAL(20,3),
  Latitude  DECIMAL(20,3),
  Direction  DECIMAL(20,3),
  Comment varchar(250) NOT NULL,
  HasStopZone boolean NOT NULL,
  HasLongStopZone boolean NOT NULL,
  DistrictId INT,
  SegmentId INT,
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);

CREATE TABLE IF NOT EXISTS vehicle (
  Id SERIAL,
  Model varchar(250) NOT NULL,
  Year int NOT NULL,
  DeviceId INT,
  ProviderId INT,
  IsOwned boolean NOT NULL,
  ManufacturerId INT,
  VehicleTypeId INT,
  Comment varchar(250) NOT NULL,
  PhoneNumber varchar(250) NOT NULL,
  LicencePlate varchar(250) NOT NULL,
  BaseId INT,
  FuelConsumptionRate INT,
  FuelConsumptionRateWinter INT,
  ValidFrom TIMESTAMPTZ,
  ValidTo TIMESTAMPTZ,
  AuthorId INT NOT NULL,
  EditorId INT NOT NULL,
  CreatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdatedAt TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UpdateToken varchar(250) NOT NULL,
  PRIMARY KEY (Id)
);