version: "3.4"

services:
  referral-system-database:
    image: postgres
    container_name: referral-system-database
    environment:
      POSTGRES_USER: rs
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: referralsystem
    restart: always
    ports:
      - 5433:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=rs@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=Str0ngPass!
    restart: always
    ports:
        - "5050:80"