version: "3.4"

networks:
  referral-system-network:
    driver: bridge

services:

  database.referralsystem:
    container_name: referral-system-database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: rs
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: referralsystem
      POSTGRES_ADMIN_PASSWORD: Str0ngPass!
    ports:
      - 5433:5432
    networks:
      - referral-system-network